AvondaleTyresOnlineShop/Components/TopProductsViewComponent.cs
using AvondaleTyresOnlineShop.Repository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AvondaleTyresOnlineShop.Components
{
    
        public class TopProductsViewComponent : ViewComponent
        {
        private readonly IProductRepository _productRepository;

        public TopProductsViewComponent(IProductRepository productRepository)
        {
            _productRepository = productRepository;
        }

        public async Task<IViewComponentResult> InvokeAsync(int count)
        {
            var products = await _productRepository.GetTopProductsAsync(count);
            return View(products);
        }
        }
    
}

AvondaleTyresOnlineShop/Controllers/HomeController.cs
using AvondaleTyresOnlineShop.Models;
using AvondaleTyresOnlineShop.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AvondaleTyresOnlineShop.Controllers
{
    public class HomeController : Controller
    {
       
        private readonly ILogger<HomeController> _logger;
        private readonly NewProductAlertConfig _newProductAlertconfiguration;
        private readonly NewProductAlertConfig _thirdPartyProductconfiguration;
        private readonly IMessageRepository _messageRepository;
        private readonly IConfiguration configuration;

        public HomeController(ILogger<HomeController> logger, 
            IOptionsSnapshot<NewProductAlertConfig> newProductAlertconfiguration, 
            IMessageRepository messageRepository)
        {
            _logger = logger;
            _newProductAlertconfiguration = newProductAlertconfiguration.Get("InternalProduct");
            _thirdPartyProductconfiguration = newProductAlertconfiguration.Get("ThirdPartyProduct");
            _messageRepository = messageRepository;
        }

        public ViewResult Index()
        {
            //bool isDisplay = _newProductAlertconfiguration.DisplayNewProductAlert;
            //bool isDisplay1 = _thirdPartyProductconfiguration.DisplayNewProductAlert;

           //var value = _messageRepository.GetName();

            //var newProduct = configuration.GetSection("NewProductAlert");
            //var result = newProduct.GetValue<bool>("DisplayNewProductAlert");
            //var productName = newProduct.GetValue<string>("ProductName");

            //var result = configuration["AppName"];
            //var key1 = configuration["infoObj:key1"];
            //var key2 = configuration["infoObj:key2"];
            //var key3 = configuration["infoObj:key3:key3obj1"];
            return View();
        }

        public ViewResult AboutUs()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        public ViewResult ContactUs()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AvondaleTyresOnlineShop/Views/Home/AboutUs.cshtml
@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AboutUs</title>
</head>
<body>
    <h1>This is the about page of application</h1>
</body>
</html>

AvondaleTyresOnlineShop/Views/Home/ContactUs.cshtml
@{

    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Contact Us</h1>

AvondaleTyresOnlineShop/Views/Home/Index.cshtml
@{ ViewData["Title"] = "Home"; }
<section class="jumbotron text-center">
    <div class="container">
        <h1>Welcome to Avondale Tyres Online Shop</h1>
        <p class="lead text-muted">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
        </p>
        <p>
            <a href="#" class="btn btn-primary my-2">Search Products</a>
        </p>
    </div>
</section>

<div class="py-5 bg-light">
    <div class="container">
        <h3 class="h3">HOT Selling</h3>
        @*@await Component.InvokeAsync("TopProduct", new { count = 3 })*@
        @*@await Component.InvokeAsync("TopProducts")*@

        @*<vc:top-products></vc:top-products>*@
        <div class="row">
            <div class="col-md-4">
                <partial name="_productThumbnail" model="new ProductModel()" />
            </div>
            <div class="col-md-4">
                <partial name="_productThumbnail" model="new ProductModel()" />
            </div>
            <div class="col-md-4">
                <partial name="_productThumbnail" model="new ProductModel()" />
            </div>
        </div>
    </div>
</div>




@section scripts{
    <script>
        $(document).ready(function () {
            //alert("document is ready");
        })
    </script>
}